export { HomePageBlock } from './HomePageBlock'
export { LeftBlock } from './LeftBlock'
export { MainLayout } from './MainLayout'
export { RightBlock } from './RightBlock'
export { WithRightBlock } from './WithRightBlock'