export { LocationComponent } from './LocationComponent'
export { Profile } from './Profile'
export { Setting } from './Setting'
export { SocialLink } from './SocialLink'
export { ToVisit } from './ToVisit'